// <auto-generated />
using System;
using InsurancePlatform.ProposalService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsurancePlatform.ProposalService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProposalDbContext))]
    partial class ProposalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InsurancePlatform.ProposalService.Domain.Aggregates.Proposals.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("proposals", (string)null);
                });

            modelBuilder.Entity("InsurancePlatform.ProposalService.Domain.Aggregates.Proposals.Proposal", b =>
                {
                    b.OwnsOne("InsurancePlatform.ProposalService.Domain.ValueObjects.CoverageAmount", "CoverageAmount", b1 =>
                        {
                            b1.Property<Guid>("ProposalId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("coverage_amount");

                            b1.HasKey("ProposalId");

                            b1.ToTable("proposals");

                            b1.WithOwner()
                                .HasForeignKey("ProposalId");
                        });

                    b.OwnsOne("InsurancePlatform.ProposalService.Domain.ValueObjects.CustomerName", "CustomerName", b1 =>
                        {
                            b1.Property<Guid>("ProposalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("customer_name");

                            b1.HasKey("ProposalId");

                            b1.ToTable("proposals");

                            b1.WithOwner()
                                .HasForeignKey("ProposalId");
                        });

                    b.OwnsOne("InsurancePlatform.ProposalService.Domain.ValueObjects.InsuranceType", "InsuranceType", b1 =>
                        {
                            b1.Property<Guid>("ProposalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("insurance_type");

                            b1.HasKey("ProposalId");

                            b1.ToTable("proposals");

                            b1.WithOwner()
                                .HasForeignKey("ProposalId");
                        });

                    b.Navigation("CoverageAmount")
                        .IsRequired();

                    b.Navigation("CustomerName")
                        .IsRequired();

                    b.Navigation("InsuranceType")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
